### ISSUE TITLE
Error: When I use the Preprocessing

### ISSUE THREAD

**Issue by Brinks0211** [YongLiuLab/brant#7]
error:
No *.nii files were found in

出错 brant_get_subjs (line 27)
        [nifti_list, subj_ids] = brant_get_subjs_multi4d_single3d(input_nmpos, input_dirs, data_input.filetype,
        'single3d', check_tps_ind);

出错 brant_preprocess_jobman (line 64)
        [nifti_list_tmp, subj_ids] = brant_get_subjs(data_input_tmp);

出错 brant_preprocess>run_cb (line 343)
brant_preprocess_jobman(jobman, gcf);
 
计算 UIControl Callback 时出错

Detail:
After using the convert Dicom ( Uncheck the delete first N timepoints because it would remind error), I submitted the output data to the Preccessing and the Matlab remind me the error above.

**Comment by gourdchen** [comment]
Would you please provide the detail information? Please give me the screenshot of the brant window.

**Comment by Brinks0211** [comment]
Thanks for your attention. I found the cause was that the nifit files were forgotten to rename. 
But now I have a new question.
I update the matlab to 2020b and intsall the brant . 
When I try to boot the brant , 
The error says: 

错误使用 matlab.graphics.Graphics/set
类 AnnotationPane 的属性 Units 无法识别。

出错 brant (第 33 行)
            set(allchild(h_fig), 'Units', 'characters');
So I can't propress the nifit files. The error also occurred in Matlab 2021a and 2021b.
I used to download the  AnnotationPane patch (guidefunc.m) and unfortunately it doesn't work.

**Comment by Brinks0211** [comment]
![屏幕截图 2023-03-07 205742](https://user-images.githubusercontent.com/67633648/223428800-9ca93542-a082-4df0-a2e5-42a7f27d1ab7.png)

**Comment by gourdchen** [comment]
We have noticed this mistake. It is an error about the GUI, which is not impacting the image processing function. You can ignore it.

**Comment by Brinks0211** [comment]
Thanks for your replying. Get it.发自我的荣耀手机-------- 原始邮件 --------发件人： PindongChen ***@***.***>日期： 2023年3月7日周二 21:01收件人： YongLiuLab/brant ***@***.***>抄送： Brinks0211 ***@***.***>, State change ***@***.***>主    题： Re: [YongLiuLab/brant] Error: When I use the Preprocessing (Issue #7)
We have noticed this mistake. It is an error about the GUI, which is not impacting the image processing function. You can ignore it.
